---
- name: Add Nvidia GPG apt Key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add Nvidia Repository Part 1
  apt_repository:
    repo: deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
    state: present

- name: Add Nvidia Repository Part 2
  apt_repository:
    repo: deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
    state: present

- name: Update apt and install nvidia-container-toolkit & nvidia-driver
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: ["nvidia-container-toolkit", "nvidia-driver-535"]

- name: Hold nvidia-driver-535 nvidia-container-toolkit
  command: >
    apt-mark hold nvidia-driver-535 nvidia-container-toolkit
  ignore_errors: True
