---
- name: Update apt cache
  apt: update_cache=true cache_valid_time=3600

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop: ["apt-transport-https", "software-properties-common", "ca-certificates", "curl", "python3-pip"]

- name: Add Docker GPG apt Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install docker-compose
  remote_user: ubuntu
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Enable Docker CE service at startup
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
