---
- name: Update apt cache
  apt: update_cache=true cache_valid_time=3600

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: ["apt-transport-https", "software-properties-common", "ca-certificates", "curl", "zip", "unzip", "nvtop", "jq", "python3-pip"]

- name: Add Docker GPG apt Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: true

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install docker-compose
  remote_user: ubuntu
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Ensure docker users are added to the docker group.
  user:
    name: admin
    groups: [ 'docker' ]
    append: yes

- name: Add custom docker `daemon.json` file
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
