name: Security vulnerability scanner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  vulnerability-scanner:
    name: Security vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          skip-files: 'docker-compose.yml'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
